### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by tjroune** [BKeyport/homebridge-davisfixed#2]
I am using WiFiLogger 2 on my Vantage Pro. After configuring the plugin (following the instructions), I keep getting a syntax error. I have copied and pasted the error from my Homebridge Log.

SyntaxError: Unexpected token F in JSON at position 0
    at JSON.parse (<anonymous>)
    at davis.<anonymous> (/usr/local/lib/node_modules/homebridge-davis/index.js:106:28)
    at Request._callback (/usr/local/lib/node_modules/homebridge-davis/index.js:45:4)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-davis/node_modules/request/request.js:185:22)
    at Request.emit (node:events:514:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-davis/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:514:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-davis/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)

**Comment by BKeyport** [comment]
This is pointing to the json received from your weather unit. Is it possible for you to do two things: 

1) Share your URL you're using (IP/Name don't matter, so you can blank that if you want) 
2) manually run it via your web browser, by pasting the URL into the browser, then posting the output. 

Thanks!

**Comment by tjroune** [comment]
![Screen Shot 2023-09-10 at 16 34 13 PM](https://github.com/BKeyport/homebridge-davis/assets/29844097/b58b1db5-a5c9-4692-ba2c-59fbbbfa3385)

I get the screen I post here (which is my regular Wifilogger Home Screen) when I use just the IP address (and nothing else). If I put the IP address in this format (http://ip address/v1/current conditions) and run it in a web browser, I get a blank screen with FileNotFound in the upper left.

When I put just the IP address (and nothing else) in URL in the Homebridge plugin configuration, I will get Request to Davis API failed: Invalid URI "my-ip-address" in the Homebridge log.

**Comment by BKeyport** [comment]
Okay, I see the problem. You're not using the VantagePro directly. 

The Syntax error is the Wifilogger rightfully telling you that the URL is invalid. 

You need to move the URL to http://address_of_vantage_pro/v1/current_conditions 

This *requires* direct access to the IP address of the Vantage pro, not any interpretative in-betweens. 

For example: http://192.168.0.6/v1/current_conditions is my weatherlink device (Vantage Pro2).. When I query it, I get
```
{"data":{"did":"001D0A71573B","ts":1694396793,"conditions":[{"lsid":434637,"data_structure_type":1,"txid":1,"temp": 72.7,"hum":44.4,"dew_point": 49.8,"wet_bulb": 56.1,"heat_index": 71.5,"wind_chill": 72.7,"thw_index": 71.5,"thsw_index":null,"wind_speed_last":2.00,"wind_dir_last":342,"wind_speed_avg_last_1_min":1.56,"wind_dir_scalar_avg_last_1_min":343,"wind_speed_avg_last_2_min":1.25,"wind_dir_scalar_avg_last_2_min":337,"wind_speed_hi_last_2_min":6.00,"wind_dir_at_hi_speed_last_2_min":340,"wind_speed_avg_last_10_min":1.37,"wind_dir_scalar_avg_last_10_min":325,"wind_speed_hi_last_10_min":6.00,"wind_dir_at_hi_speed_last_10_min":349,"rain_size":1,"rain_rate_last":0,"rain_rate_hi":0,"rainfall_last_15_min":0,"rain_rate_hi_last_15_min":0,"rainfall_last_60_min":0,"rainfall_last_24_hr":0,"rain_storm":0,"rain_storm_start_at":null,"solar_rad":null,"uv_index":null,"rx_state":0,"trans_battery_flag":0,"rainfall_daily":0,"rainfall_monthly":16,"rainfall_year":16,"rain_storm_last":16,"rain_storm_last_start_at":1693785601,"rain_storm_last_end_at":1693926060},{"lsid":434634,"data_structure_type":4,"temp_in": 85.3,"hum_in":36.2,"dew_point_in": 55.5,"heat_index_in": 84.3},{"lsid":434633,"data_structure_type":3,"bar_sea_level":30.061,"bar_trend": 0.006,"bar_absolute":29.597}]},"error":null}
```

This is the only way the module is going to work, and I cannot and will not adjust to other methods unless Davis drops direct access to the weatherlink protocals.
