### ISSUE TITLE
Support for multiple devices

### ISSUE THREAD

**Issue by Jeff-Meadows** [BKeyport/homebridge-davisfixed#5]
I have a Vantage Vue and 2 AirLink devices. Each has its own local IP address, but I can only configure this plugin to work with one of them at a time. Is there a way to support more than one device?

**Comment by BKeyport** [comment]
There should be a button at the bottom of the GUI config window to add a device, it'll have all the same options as the original.

**Comment by Jeff-Meadows** [comment]
Thanks!
